name: "Build and Push Docker Image to ECR"

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags (e.g., v1.0.0)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to ECR
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          TAG=${{ github.ref_name }}
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/$ECR_REPOSITORY:$TAG"

          docker build -t $IMAGE_URI ./simple_node_app
          docker push $IMAGE_URI
